### ISSUE TITLE
[server] Add friends related db schema changes and queries.

### ISSUE THREAD

**Issue by Kuchteq** [ISDC-Helsinki/splitbit#22]
Friends in SplitBit don't work like in social media. You only become friends once you create/get added to a group. They are just meant to make it easier for creating subsequent groups with the same people as those contacts get saved.

- [ ] Modify the database schema to include a new join table **friends** for many-to-many relationships between user_1 and user_2.
- [x] Add an sqlc query to queries.sql called GetFriendsOfUser doing exactly how it is self described but also getting how many groups the user and the friend is a part of together.

Handling adding friends is done on the create route handler and will be within the scope of that task.

**Comment by jakubgrad** [comment]
Friends are always the people who are in the same group. You make friends when they're added to the same group as yours. Hence a friends group is not necessary

**Comment by Kuchteq** [comment]
Good catch! Merged your changes!
