### ISSUE TITLE
[web] Handle user login

### ISSUE THREAD

**Issue by Kuchteq** [ISDC-Helsinki/splitbit#3]
Currently, the groups which the user sees/can access isn't limited to their account. We want to change that by implementing the login functionality on the web client.
- [x] Make necessary forms/text fields to handle passing the login data. Those include the instance url, username and password. Do this as a seperate route available under /login. Reference: https://kit.svelte.dev/docs/routing. The UI that handles it should look like: https://www.figma.com/design/lzUOvguPdSF8103bGHBnDX/Split?node-id=0-1&t=YZP5CRpQmUWGEy0Q-1
- [x] Prepare the server request and response typescript model.
- [x] Use the fetch API inside the route file for logging in use the request and response model. https://www.w3schools.com/js/js_api_fetch.asp
- [x] Store the returned token as a httpOnly, secure cookie https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#block_access_to_your_cookies
- [x] Extract username and userID from the JWT token and also store it inside localStorage https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by ireshh** [comment]
hello, world

**Comment by ozkanali357** [comment]
goodmorning

**Comment by ireshh** [comment]
moi moi

**Comment by kirkeruusalu** [comment]
pull request time!!!
